services:
  ubuntu:
    build: ./ubuntu-dockerfile/
    tty: true
  postgresql:
    image: "postgres:17.2-alpine3.21"
    ports:
      - "5432:5432"
    env_file:
      - path: ./postgres.env
        required: true
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.bridge.name: "task-2-network"